### ISSUE TITLE
ResourceManager의 File Load 시점 변경 요청

### ISSUE THREAD

**Issue by CrustPizza** [COMETLEEE/DUOL#28]
![image](https://user-images.githubusercontent.com/53199927/205586405-2f234298-5cc2-43ec-bc53-6a3551e2d14c.png)

초기화 시점에 다 불러오기보다 불러올 파일 내역을 저장하고 있다가

로딩 씬을 만드는 방향으로 바꿨으면 좋겠습니다.

지금은 Init에서 너무 많은 작업을 하고 있어서 프로그램 실행 시에 끼워 넣는? 작업을 할만한 여지가 부족합니다.

**Comment by COMETLEEE** [comment]
지금 확인했네요. 다음과 같은 경우는 아직 개발 중이여서 테스트 코드에 해당합니다. 

ResourceManager Initialize 에서는 Editor 또는 Engine에서 디폴트로 사용하는 요소들만 이니셜라이즈하고

클라이언트에 사용되는 리소스들은 다른 시점에 (로딩 씬 등의 구현) 로드될 계획입니다.
