### ISSUE TITLE
Rigidbody Component에서 Axis Lock 개별 및 전체 나누어서 Lock시키도록 기능 추가 요청

### ISSUE THREAD

**Issue by CrustPizza** [COMETLEEE/DUOL#30]
![image](https://user-images.githubusercontent.com/53199927/208589600-e3151493-1136-4a6b-b004-8359126d69d2.png)

현재 모든 회전을 얼리는 작업만 가능한데 개별 잠금 기능 추가 요청합니다.

![image](https://user-images.githubusercontent.com/53199927/208591412-362fa7c2-1dc7-47e6-9106-6f37723fcf07.png)

그리고 저 함수의 내부 코드에서 호환되지 않는 작업(여러 축을 동시에 적용 시키기, 사용하면 안되는 NONE 사용)이 있어서

여러 축 잠금 기능을 추가 구현해서 병합시켜두었습니다. 이거 반영해서 수정 부탁드립니다.

![image](https://user-images.githubusercontent.com/53199927/208591352-e9c31c3a-1d83-48ec-bc54-74ce1afb0127.png)

![image](https://user-images.githubusercontent.com/53199927/208591610-9ab13cee-8061-4379-bfed-c5e1488bf0a9.png)

**Comment by COMETLEEE** [comment]
좋은 기능의 추가입니다. 수정 완료하였습니다 !
